language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "Q/ePAKgUtWNgaFul0HLY64XKWoYiOzFxTrFEJhK7cg5EPDHAliSogJ3FPFRO1wxQo8z3MUirxeCU0GrMFbAOLeRUAP3pDedAjIDrssutVj5wy5rc18jZ0IGX0f+Wx47SLKqC9iA4wD6oq0WSOH01c/9fDhNjV2+fEssH6AJla8lvAFeYlEkDZ3/VstnIDqv9KN+r7SkI00oWf8j8fhsl07SG3jiHmaEMvfy7ZwQ/atSTsJPpmXm/kLj73BHnZ0brOwiw7KRo+GxtLcdOdl/tN5Ap6Zbc2wT+GRM07MVaDfKzlnnDZVN2PlmeAmGKl9usudbzReQodU0OdgOfywt+ZQNNszVc9I7RejRKXzOU415UYWeek7tflhw7P9VoMMxXGEsXIf9CtTx6CHMET7HDiZi4/DInHHcB5r01wPI+jamVZYLbj5w4HVxauQa9RHuhtiBxkt9Q5sg94NeymSY8BvLPSCyx8icisZSCx2LhSGway/OZnt87cJbS3HoAHGWF8WXRacgJEBRDz//za7sqrFIUMIcIbOf/+/otu4eQpLYzFzndneuAzmTPtCSy8R/nVvMGYahm44K7hkgu+14wbdT8fXpHnqbDzW2A8PAEDhW7LT97deXdyWYOC9WiRzEJi44KZOJFaItz05l5LZVKdDuN1xvBjsGYkOKEmYpB6HU="
    - secure: "Ysz/5vqRzjuPhwSVcBgf39EYpmmIK+3whqjgwpvfedRn/xNX0FbS5OyrWSa45EgZx/wEHjPh0HrsqygdlxYYxe2yseTdVMBbTqjbj/FNmGeStT2mY7B1QofIVISNDgRphYH5gkIOjCIPVRY94lvcfwY65/JUweQqvvOQjtDM0bq/Dna7lbL4C6/CJE823pNU0ZchGEm/p+hq7jBvu3xhgSOnfhOLOxsQM/M2zVUyUFer775AE/8xCXJh0whS6D/9366RPzrQXk1qagocSqeXFziM/T5/S2O1uubP4OAQl+RiEdEXyvJkFgsXl64qkKmTNdVBUHiIMWtdXAvyhQ7B1SPr7FTBdTTW/D1k83kM5AJbQzmchRnsqSKo7P7kE6MbFZfeaLx1d5dfUVgMIke9JHxqaeSePTAm8BF8E4O9AO2JAJUyyWUpU/kKTBaqwPBSNN88vncGjy5tnpP9qq+2YhIEcQe4X1mLm+PESWi+Fsr5iNBqrCbw/DP/+VjfKJ/tEs/F0MYRv7Y4r0yXkODtg9IMuf4FhdCJtCs1qFzkB7SBuT3Xubm4KNDdX/n06QNxd3oSEpbWkGhckDj4S0IPahioVtbjuAxTChT+osjoQsdRHEUzjA0mG8ffz1hCZ5ZfSqMj4iAWKmshhIFSKPXLg6b7kmiAuZVp3Zny44imagM="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
